
[[local|localrc]]
#credential
SERVICE_TOKEN=azertytoken
ADMIN_PASSWORD=secret
MYSQL_PASSWORD=secret
RABBIT_PASSWORD=secret
SERVICE_PASSWORD=$ADMIN_PASSWORD



#network
FLAT_INTERFACE=eth0
FLOATING_RANGE=10.241.254.0/24

PUBLIC_NETWORK_GATEWAY=10.241.254.253
FIXED_RANGE=192.168.1.0/24
NETWORK_GATEWAY=192.168.1.1
FIXED_NETWORK_SIZE=256
#HOST_IP=

#multi_host
MULTI_HOST=1


# Enable Logging
LOGFILE=/opt/stack/logs/stack.sh.log
VERBOSE=True
LOG_COLOR=True
SCREEN_LOGDIR=/opt/stack/logs

#service
disable_service nnet
enable_service qsvc
enable_service qagt
enable_service qdhcp
enable_service ql3
enable_service qmeta
enable_service neutron
enable_service qfwaas
enable_service qvpn
enable_service qlbaas
Q_PLUGIN=ml2
Q_ML2_TENANT_NETWORK_TYPE=vxlan
